# Generated by Django 5.2.5 on 2025-11-20 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio Unitario')),
                ('stock_actual', models.IntegerField(verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(verbose_name='Stock Mínimo Crítico')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_mano_obra', models.IntegerField(verbose_name='Precio Base Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_pagar', models.IntegerField(default=0)),
                ('descuento_aplicado', models.BooleanField(default=False, verbose_name='Descuento Cumpleaños Aplicado')),
                ('estilista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Estilista a cargo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestionApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAtencionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad Usada')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionApp.atencion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestionApp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='productos',
            field=models.ManyToManyField(through='GestionApp.DetalleAtencionProducto', to='GestionApp.producto'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestionApp.servicio'),
        ),
    ]
