# Generated by Django 5.2.5 on 2025-11-20 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('contacto_nombre', models.CharField(max_length=100, verbose_name='Nombre Contacto')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('productos_suministrados', models.TextField(verbose_name='Productos que suministra')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('cargo', models.CharField(choices=[('ESTILISTA', 'Estilista'), ('RECEPCIONISTA', 'Recepcionista'), ('ADMINISTRADOR', 'Administrador'), ('LIMPIEZA', 'Personal de Limpieza')], max_length=20, verbose_name='Cargo')),
                ('sueldo', models.IntegerField(verbose_name='Sueldo Base')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema')),
            ],
        ),
    ]
