# Generated by Django 5.2.5 on 2025-11-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0002_proveedor_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Producto Activo'),
        ),
    ]
