# Generated by Django 5.2.5 on 2025-12-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0003_producto_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='servicio',
        ),
        migrations.AddField(
            model_name='atencion',
            name='servicios',
            field=models.ManyToManyField(to='GestionApp.servicio', verbose_name='Servicios Realizados'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('ESTILISTA', 'Estilista'), ('RECEPCIONISTA', 'Recepcionista'), ('ADMINISTRADOR', 'Administrador')], max_length=20, verbose_name='Cargo'),
        ),
    ]
